"""initial phase1

Revision ID: 779fe47e76fd
Revises: 
Create Date: 2026-09-21 04:05:28.623464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '779fe47e76fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.Text(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_id')
    )
    op.create_table('checklist_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('form_name', sa.String(length=160), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('admin_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('csrf_token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('idle_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_admin_sessions_admin_user_id'), 'admin_sessions', ['admin_user_id'], unique=False)
    op.create_table('auth_lockouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=40), nullable=False),
    sa.Column('scope_key', sa.String(length=160), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_fail_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['released_by_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_type', 'scope_key', name='uq_auth_lock_scope')
    )
    op.create_index(op.f('ix_auth_lockouts_locked_until'), 'auth_lockouts', ['locked_until'], unique=False)
    op.create_table('inspection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_version_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('group_name', sa.String(length=40), nullable=False),
    sa.Column('label_official', sa.Text(), nullable=False),
    sa.Column('label_display', sa.Text(), nullable=False),
    sa.Column('official_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['checklist_version_id'], ['checklist_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checklist_version_id', 'code'),
    sa.UniqueConstraint('checklist_version_id', 'seq')
    )
    op.create_index(op.f('ix_inspection_items_checklist_version_id'), 'inspection_items', ['checklist_version_id'], unique=False)
    op.create_table('member_import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('parser_version', sa.String(length=20), nullable=False),
    sa.Column('import_type', sa.String(length=30), nullable=False),
    sa.Column('category_scope', sa.String(length=40), nullable=True),
    sa.Column('column_mapping', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('counts', sa.JSON(), nullable=True),
    sa.Column('guard_warnings', sa.JSON(), nullable=True),
    sa.Column('applied_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['applied_by_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('value_type', sa.String(length=30), nullable=False),
    sa.Column('policy_pending', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('management_number', sa.String(length=80), nullable=True),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('vehicle_number', sa.String(length=80), nullable=False),
    sa.Column('vehicle_number_norm', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('mobile', sa.String(length=40), nullable=True),
    sa.Column('master_membership_status', sa.String(length=40), nullable=True),
    sa.Column('certificate_number', sa.String(length=80), nullable=True),
    sa.Column('vehicle_type', sa.String(length=160), nullable=True),
    sa.Column('business_name', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('tracking_start_date', sa.Date(), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inactive_reason', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('last_import_batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['last_import_batch_id'], ['member_import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_active'), 'members', ['active'], unique=False)
    op.create_index(op.f('ix_members_category'), 'members', ['category'], unique=False)
    op.create_index(op.f('ix_members_certificate_number'), 'members', ['certificate_number'], unique=False)
    op.create_index(op.f('ix_members_management_number'), 'members', ['management_number'], unique=False)
    op.create_index(op.f('ix_members_mobile'), 'members', ['mobile'], unique=False)
    op.create_index(op.f('ix_members_name'), 'members', ['name'], unique=False)
    op.create_index(op.f('ix_members_region'), 'members', ['region'], unique=False)
    op.create_index(op.f('ix_members_vehicle_number_norm'), 'members', ['vehicle_number_norm'], unique=False)
    op.create_index(op.f('ix_members_vehicle_type'), 'members', ['vehicle_type'], unique=False)
    op.create_index('uq_members_active_vehicle', 'members', ['vehicle_number_norm'], unique=True, postgresql_where=sa.text('active = true'), sqlite_where=sa.text('active = 1'))
    op.create_table('admin_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('admin_role', sa.String(length=30), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=60), nullable=True),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('before_value', sa.JSON(), nullable=True),
    sa.Column('after_value', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=80), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_action_logs_action'), 'admin_action_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_action_logs_admin_user_id'), 'admin_action_logs', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_action_logs_member_id'), 'admin_action_logs', ['member_id'], unique=False)
    op.create_index(op.f('ix_admin_action_logs_occurred_at'), 'admin_action_logs', ['occurred_at'], unique=False)
    op.create_table('compliance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_member_id', sa.Integer(), nullable=True),
    sa.Column('actor_admin_id', sa.Integer(), nullable=True),
    sa.Column('original_event_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['actor_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['original_event_id'], ['compliance_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_events_member_id'), 'compliance_events', ['member_id'], unique=False)
    op.create_index(op.f('ix_compliance_events_target_date'), 'compliance_events', ['target_date'], unique=False)
    op.create_table('driver_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('pin_hash', sa.Text(), nullable=True),
    sa.Column('pepper_version', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('pin_set_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['reset_by_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_accounts_member_id'), 'driver_accounts', ['member_id'], unique=True)
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('checklist_version_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('first_entered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_revision_no', sa.Integer(), nullable=False),
    sa.Column('entry_channel', sa.String(length=30), nullable=False),
    sa.Column('entered_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('is_late_entry', sa.Boolean(), nullable=False),
    sa.Column('proxy_method', sa.String(length=40), nullable=True),
    sa.Column('proxy_reason', sa.Text(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status in ('normal','issue','not_driving')"),
    sa.ForeignKeyConstraint(['checklist_version_id'], ['checklist_versions.id'], ),
    sa.ForeignKeyConstraint(['entered_by_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'inspection_date', name='uq_inspection_member_date')
    )
    op.create_index(op.f('ix_inspections_inspection_date'), 'inspections', ['inspection_date'], unique=False)
    op.create_index(op.f('ix_inspections_is_late_entry'), 'inspections', ['is_late_entry'], unique=False)
    op.create_index(op.f('ix_inspections_member_id'), 'inspections', ['member_id'], unique=False)
    op.create_index(op.f('ix_inspections_status'), 'inspections', ['status'], unique=False)
    op.create_table('member_change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=40), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('requested_via', sa.String(length=30), nullable=False),
    sa.Column('decided_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_change_requests_member_id'), 'member_change_requests', ['member_id'], unique=False)
    op.create_index(op.f('ix_member_change_requests_status'), 'member_change_requests', ['status'], unique=False)
    op.create_table('member_import_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('management_number', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('vehicle_number', sa.String(length=80), nullable=True),
    sa.Column('vehicle_number_norm', sa.String(length=80), nullable=True),
    sa.Column('mobile', sa.String(length=40), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('matched_member_id', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(length=40), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['member_import_batches.id'], ),
    sa.ForeignKeyConstraint(['matched_member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_import_rows_batch_id'), 'member_import_rows', ['batch_id'], unique=False)
    op.create_index(op.f('ix_member_import_rows_classification'), 'member_import_rows', ['classification'], unique=False)
    op.create_table('trusted_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('app_version', sa.String(length=40), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_ip', sa.String(length=64), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_trusted_devices_member_id'), 'trusted_devices', ['member_id'], unique=False)
    op.create_table('driver_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('login_ip', sa.String(length=64), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['trusted_devices.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_driver_sessions_expires_at'), 'driver_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_driver_sessions_member_id'), 'driver_sessions', ['member_id'], unique=False)
    op.create_table('inspection_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('action_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['inspection_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id', 'item_id')
    )
    op.create_index(op.f('ix_inspection_results_inspection_id'), 'inspection_results', ['inspection_id'], unique=False)
    op.create_table('inspection_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('problem_items', sa.JSON(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_member_id', sa.Integer(), nullable=True),
    sa.Column('actor_admin_id', sa.Integer(), nullable=True),
    sa.Column('entry_channel', sa.String(length=30), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('client_request_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['actor_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_request_id'),
    sa.UniqueConstraint('inspection_id', 'revision_no')
    )
    op.create_index(op.f('ix_inspection_revisions_inspection_id'), 'inspection_revisions', ['inspection_id'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('attempt_type', sa.String(length=40), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_number_norm_input', sa.String(length=100), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=40), nullable=False),
    sa.Column('lock_scope', sa.String(length=40), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['trusted_devices.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_ip'), 'login_attempts', ['ip'], unique=False)
    op.create_index(op.f('ix_login_attempts_member_id'), 'login_attempts', ['member_id'], unique=False)
    op.create_index(op.f('ix_login_attempts_occurred_at'), 'login_attempts', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_attempts_occurred_at'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_member_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_ip'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_inspection_revisions_inspection_id'), table_name='inspection_revisions')
    op.drop_table('inspection_revisions')
    op.drop_index(op.f('ix_inspection_results_inspection_id'), table_name='inspection_results')
    op.drop_table('inspection_results')
    op.drop_index(op.f('ix_driver_sessions_member_id'), table_name='driver_sessions')
    op.drop_index(op.f('ix_driver_sessions_expires_at'), table_name='driver_sessions')
    op.drop_table('driver_sessions')
    op.drop_index(op.f('ix_trusted_devices_member_id'), table_name='trusted_devices')
    op.drop_table('trusted_devices')
    op.drop_index(op.f('ix_member_import_rows_classification'), table_name='member_import_rows')
    op.drop_index(op.f('ix_member_import_rows_batch_id'), table_name='member_import_rows')
    op.drop_table('member_import_rows')
    op.drop_index(op.f('ix_member_change_requests_status'), table_name='member_change_requests')
    op.drop_index(op.f('ix_member_change_requests_member_id'), table_name='member_change_requests')
    op.drop_table('member_change_requests')
    op.drop_index(op.f('ix_inspections_status'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_member_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_is_late_entry'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_inspection_date'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_driver_accounts_member_id'), table_name='driver_accounts')
    op.drop_table('driver_accounts')
    op.drop_index(op.f('ix_compliance_events_target_date'), table_name='compliance_events')
    op.drop_index(op.f('ix_compliance_events_member_id'), table_name='compliance_events')
    op.drop_table('compliance_events')
    op.drop_index(op.f('ix_admin_action_logs_occurred_at'), table_name='admin_action_logs')
    op.drop_index(op.f('ix_admin_action_logs_member_id'), table_name='admin_action_logs')
    op.drop_index(op.f('ix_admin_action_logs_admin_user_id'), table_name='admin_action_logs')
    op.drop_index(op.f('ix_admin_action_logs_action'), table_name='admin_action_logs')
    op.drop_table('admin_action_logs')
    op.drop_index('uq_members_active_vehicle', table_name='members', postgresql_where=sa.text('active = true'), sqlite_where=sa.text('active = 1'))
    op.drop_index(op.f('ix_members_vehicle_type'), table_name='members')
    op.drop_index(op.f('ix_members_vehicle_number_norm'), table_name='members')
    op.drop_index(op.f('ix_members_region'), table_name='members')
    op.drop_index(op.f('ix_members_name'), table_name='members')
    op.drop_index(op.f('ix_members_mobile'), table_name='members')
    op.drop_index(op.f('ix_members_management_number'), table_name='members')
    op.drop_index(op.f('ix_members_certificate_number'), table_name='members')
    op.drop_index(op.f('ix_members_category'), table_name='members')
    op.drop_index(op.f('ix_members_active'), table_name='members')
    op.drop_table('members')
    op.drop_table('system_settings')
    op.drop_table('member_import_batches')
    op.drop_index(op.f('ix_inspection_items_checklist_version_id'), table_name='inspection_items')
    op.drop_table('inspection_items')
    op.drop_index(op.f('ix_auth_lockouts_locked_until'), table_name='auth_lockouts')
    op.drop_table('auth_lockouts')
    op.drop_index(op.f('ix_admin_sessions_admin_user_id'), table_name='admin_sessions')
    op.drop_table('admin_sessions')
    op.drop_table('checklist_versions')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
